In [1]:
data = "./data"

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import pandas as pd
import random
import math
import time
from sklearn.linear_model import LinearRegression, BayesianRidge
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.metrics import mean_squared_error, mean_absolute_error
import datetime
import operator
plt.style.use('seaborn')
%matplotlib inline

In [3]:
import os

confirmed_df = pd.read_csv(os.path.join(data, "time_series_covid_19_confirmed.csv"))
deaths_df = pd.read_csv(os.path.join(data, "time_series_covid_19_deaths.csv"))
recoveries_df = pd.read_csv(os.path.join(data, "time_series_covid_19_recovered.csv"))

In [4]:
confirmed_df.head()

Province/State Country/Region      Lat      Long  1/22/20  1/23/20  1/24/20  \
0            NaN       Thailand  15.0000  101.0000        2        3        5   
1            NaN          Japan  36.0000  138.0000        2        1        2   
2            NaN      Singapore   1.2833  103.8333        0        1        3   
3            NaN          Nepal  28.1667   84.2500        0        0        0   
4            NaN       Malaysia   2.5000  112.5000        0        0        0   

   1/25/20  1/26/20  1/27/20  ...  3/10/20  3/11/20  3/12/20  3/13/20  \
0        7        8        8  ...       53       59       70       75   
1        2        4        4  ...      581      639      639      701   
2        3        4        5  ...      160      178      178      200   
3        1        1        1  ...        1        1        1        1   
4        3        4        4  ...      129      149      149      197   

   3/14/20  3/15/20  3/16/20  3/17/20  3/18/20  3/19/20  
0       82      114      147      177      212      272  
1      773      839      825      878      889      924  
2      212      226      243      266      313      345  
3        1        1        1        1        1        1  
4      238      428      566      673      790      900  

[5 rows x 62 columns]

In [5]:
cols = confirmed_df.keys()

In [6]:
print(cols)

Index(['Province/State', 'Country/Region', 'Lat', 'Long', '1/22/20', '1/23/20',
       '1/24/20', '1/25/20', '1/26/20', '1/27/20', '1/28/20', '1/29/20',
       '1/30/20', '1/31/20', '2/1/20', '2/2/20', '2/3/20', '2/4/20', '2/5/20',
       '2/6/20', '2/7/20', '2/8/20', '2/9/20', '2/10/20', '2/11/20', '2/12/20',
       '2/13/20', '2/14/20', '2/15/20', '2/16/20', '2/17/20', '2/18/20',
       '2/19/20', '2/20/20', '2/21/20', '2/22/20', '2/23/20', '2/24/20',
       '2/25/20', '2/26/20', '2/27/20', '2/28/20', '2/29/20', '3/1/20',
       '3/2/20', '3/3/20', '3/4/20', '3/5/20', '3/6/20', '3/7/20', '3/8/20',
       '3/9/20', '3/10/20', '3/11/20', '3/12/20', '3/13/20', '3/14/20',
       '3/15/20', '3/16/20', '3/17/20', '3/18/20', '3/19/20'],
      dtype='object')


In [7]:
confirmed = confirmed_df.loc[:, cols[4]: cols[-1]]
deaths = deaths_df.loc[:, cols[4]: cols[-1]]
recoveries = recoveries_df.loc[:, cols[4]: cols[-1]]

In [8]:
print(confirmed)

     1/22/20  1/23/20  1/24/20  1/25/20  1/26/20  1/27/20  1/28/20  1/29/20  \
0          2        3        5        7        8        8       14       14   
1          2        1        2        2        4        4        7        7   
2          0        1        3        3        4        5        7        7   
3          0        0        0        1        1        1        1        1   
4          0        0        0        3        4        4        4        7   
..       ...      ...      ...      ...      ...      ...      ...      ...   
463        0        0        0        0        0        0        0        0   
464        0        0        0        0        0        0        0        0   
465        0        0        0        0        0        0        0        0   
466        0        0        0        0        0        0        0        0   
467        0        0        0        0        0        0        0        0   

     1/30/20  1/31/20  ...  3/10/20  3/11/20  3/12/

In [9]:
dates = confirmed.keys()
world_cases = []
total_deaths = []
mortality_rate  = []
recovery_rate = []
total_recovered = []
total_active = []

for i in dates:
    confirmed_sum = confirmed[i].sum()
    death_sum = deaths[i].sum()
    recovered_sum = recoveries[i].sum()
    world_cases.append(confirmed_sum)
    total_deaths.append(death_sum)
    mortality_rate.append(death_sum/ confirmed_sum)
    recovery_rate.append(recovered_sum/ confirmed_sum)
    total_recovered.append(recovered_sum)
    total_active.append(confirmed_sum - death_sum - recovered_sum)

In [29]:
# numpy test
x = np.array([[2,3,4,4], [5,6,7,8]])
x.reshape(-1,8 )
# numpy test complete

array([[2, 3, 4, 4, 5, 6, 7, 8]])

In [32]:
print(np.array([i for i in range(len(dates))]).reshape(-1,1))

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]
 [31]
 [32]
 [33]
 [34]
 [35]
 [36]
 [37]
 [38]
 [39]
 [40]
 [41]
 [42]
 [43]
 [44]
 [45]
 [46]
 [47]
 [48]
 [49]
 [50]
 [51]
 [52]
 [53]
 [54]
 [55]
 [56]
 [57]]


In [33]:
day_since_1_22 = np.array([i for i in range(len(dates))]).reshape(-1,1)
world_cases = np.array(world_cases).reshape(-1,1)
total_deaths = np.array(total_deaths).reshape(-1,1)
total_recovered = np.array(total_recovered).reshape(-1,1)

In [42]:
days_in_future = 10
future_forecast = np.array([i for i in range(len(dates)+ days_in_future)]).reshape(-1,1)
adjusted_dates = future_forecast[:-10]

In [43]:
print(future_forecast)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]
 [31]
 [32]
 [33]
 [34]
 [35]
 [36]
 [37]
 [38]
 [39]
 [40]
 [41]
 [42]
 [43]
 [44]
 [45]
 [46]
 [47]
 [48]
 [49]
 [50]
 [51]
 [52]
 [53]
 [54]
 [55]
 [56]
 [57]
 [58]
 [59]
 [60]
 [61]
 [62]
 [63]
 [64]
 [65]
 [66]
 [67]]


In [46]:
start = '1/22/2020'
start_date = datetime.datetime.strptime(start, '%m/%d/%Y')
future_forecast_dates = []
for i in range(len(future_forecast)):
    future_forecast_dates.append((start_date + datetime.timedelta(days=i)).strftime('%m/%d/%Y'))    

In [48]:
X_train_confirmed, X_test_confirmed, y_train_confirmed, y_test_confirmed = train_test_split(day_since_1_22, world_cases, test_size=0.15, shuffle=False)

In [ ]:
# # to find optimal paramtersfor SVR
# c = [0.01, 0.1, 1]
# gamma = [0.01, 0.1, 1]
# epsilon = [0.01, 0.1, 1]
# shrinking = [True, False]
# degree = [3,4,5]

# svm_grid = {'C': c, 'gamma': gamma, 'epsilon': epsilon, 'shrinking': shrinking, 'degree': degree}

# svm = SVR(kernel='poly')
# svm_search = RandomizedSearchCV(svm, svm_grid, scoring='neg_mean_squared_error', cv=3, return_train_score=True, n_jobs=-1, n_iter=30, verbose=1) 
# svm_search.fit(X_train_confirmed, y_train_confirmed)

In [ ]:
# svm_search.best_params_
# svm_confirmed = svm_

In [ ]:
svm_confirmed = SVR(shrinking=True, kernel='poly', gamma = 0.01, epsilon=1, degree=5, C=0.1)
svm_confirmed.fit(X_train_confirmed, y_train_confirmed)
svm_pred = svm_conf